esphome:
  name: "esp-wasserstation-wohnzimmer"
  comment: "Tierbrunnen-Annäherungs-Sensor Wohnzimmer"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<Home Assistant Encryption Key>"

ota:
  password: "<OTA Password>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wasserstation-Wohnzimmer"
    password: "<WiFi Password>"

captive_portal:

#web_server:
#  local: true

button:
  - platform: restart
    id: restartbutton
    name: "Restart"
    entity_category: "config"

sensor:
  - platform: ultrasonic
    id: tierdistance
    trigger_pin: GPIO25
    echo_pin: GPIO26
    name: "Ultraschall-Sensor"
    update_interval: 1s
    timeout: 2m

binary_sensor:
  - platform: template
    id: tiervorstation
    name: Tier vor Station
    device_class: occupancy
    filters:
      - delayed_off: 30s
    # Detect Objects 90 cm or less in front of the sensor
    lambda: |-
      if (id(tierdistance).state < 0.9) {
        // Tier vor der Station
        return true;
      } else {
        // kein Tier vor der Station
        return false;
      }
    on_press:
      then:
        - switch.turn_on: pumpe
    on_release:
      then:
        - switch.turn_off: pumpe

switch:
  - platform: gpio
    id: pumpe
    name: "Pumpe"
    pin: GPIO27
